[package]
name = "mork-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
mork-expr = { workspace=true }
pathmap = { workspace=true }
typed-arena = "2.0.2"
regex = "1.10.4"
memmap2 = "0.9.5"
